### ISSUE TITLE
uvloop error on Windows

### ISSUE THREAD

**Issue by artembeer** [EnkrateiaLucca/oreilly_live_training_llm_apps#1]
When trying to execute pip install with requirements.txt, I get the following error: 

```
Collecting uvloop==0.17.0 (from -r requirements.txt (line 212))
  Using cached uvloop-0.17.0.tar.gz (2.3 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\abeer\AppData\Local\Temp\pip-install-w45y80ub\uvloop_e32ae321c1bd42a68d9f7df62f726251\setup.py", line 8, in <module>
          raise RuntimeError('uvloop does not support Windows at the moment')
      RuntimeError: uvloop does not support Windows at the moment
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by EnkrateiaLucca** [comment]
@claude
